typography_spectrum: 0.72094
content_rating:
  adult: false
color:
  brandColors:
    - '#fffeed'
    - '#040404'
    - '#835a5d'
    - '#2c3361'
    - '#b18487'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 0.5
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.44413
analytics: {}
author:
  name: Falling Man Group
  url: ''
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/48742a79-c5bb-47e0-9118-c9cb5de2f8ff.jpg
name: Mysterium
cta: {}
navigation:
  - name: About
    id: 6e351212-ff9c-493e-a096-00cc0bc996be
    type: content
  - name: Policies
    id: a6ffbda9-54ec-4229-9d90-bd3b279b724d
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e8066f4f-634b-4d25-8a60-c2b12fc9c568.jpg
title: Mysterium
description: The annual celebration of all things Myst
purpose: []
