name: Mysterium
favicon: null
layout_spectrum: 0.44413
typography_spectrum: 0.72094
title: Mysterium
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeed'
    - '#040404'
    - '#835a5d'
    - '#2c3361'
    - '#b18487'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
