name: Mysterium
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e8066f4f-634b-4d25-8a60-c2b12fc9c568.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/48742a79-c5bb-47e0-9118-c9cb5de2f8ff.jpg
layout_spectrum: 0.44413
typography_spectrum: 0.72094
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#fffeed'
    - '#040404'
    - '#835a5d'
    - '#2c3361'
    - '#b18487'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
title: Mysterium
author:
  name: Falling Man Group
  url: ''
  email: ''
content_rating:
  adult: false
