name: Mysterium
favicon: null
layout_spectrum: 0.44413
typography_spectrum: 0.72094
title: Mysterium - The Annual Celebration of All Things MYST
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fef8ee'
    - '#472003'
    - '#b5ad97'
    - '#775941'
    - '#e8903c'
  brandStrength: 0.1875
  lightness: 0.8375358132179826
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
